<?php
/**
 * @file
 * The random_form module provides a form that will generate some random words.
 */

// keep the module name consistent throughout
global $moduleName;
$moduleName = "random";

/**
 * Implements hook_form().
 */
function random_form_form($form, &$form_state) {
  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Click Here!'),
  );
  
  return $form;
}

/**
 * Implements hook_form_validate().
 */
function random_form_form_validate($form, &$form_state) {
}

/**
 * Implements hook_form_submit().
 */
function random_form_form_submit($form, &$form_state) {
}

/**
 * Implements hook_menu().
 */
function random_form_menu() {
  $items = array();

  $items['examples/random'] = array( //this creates a URL that will call this form at "examples/random"
    'title' => 'Random Form', //page title
    'description' => 'A form to mess around with.',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('random_form_form'), //put the name of the form here
    'access callback' => TRUE
  );

  return $items;
}

